language: python
python:
- '2.7'
before_script:
- yes | python setup.py install
- git clone https://github.com/uc-cdis/dictionaryutils; cd dictionaryutils
script:
- "./run_tests.sh"
deploy:
  provider: s3
  access_key_id: AKIAZRNPHKJIKNRCX2KN
  secret_access_key:
    secure: Dco8VV+loeY760sdclg7NLWD1NGdS4SZwoNH8THOIDShXTc7T559Gh9kd58mViql4XezavwnTI70qF+nQNDuoxNouWn8uRZX9cyT5GWfK2XYBkQ06Vio8ej+64pWrPZBInvSgdQkbblzoEbX7cqWK29buyOccoMlMOgrSRaHv6iEK0ZDy6rkGMjmzaC19hfzjo1ImsrZltUPXtwn4RG4vhVq/B0EIlmJIIubzGIyN7SkQpO95GIgKt/KGo7eyn28ZjeUJYAdogEfuviewFfAZfyJyFFGUYWqr5519gg4CHaM1erW0lghNlJc+sLv+o2+VhtJEQ1Iv3LrMajSENM4/YiDfDefJ4vwcqxQVomyFbGRko8wyDG1lDER6m5p8nwMDwNFcBJXRx2R+NR/q5PvWB5dcn6G6UVVut9OqVMPHbmpTNARaC7rvOU+MSBCZk0zF9+i07iKAEsKgroi4bQ/ay31N8SFI2T6UL1hRpK0g3loqFqjAHy55Bi0wcKedm+fCntYcUS94TBQnNHfF4Irb4zOhseZmEKbE3aGLi1tg0RrUrmOSPyAc/i75USu3kwOVSsQYPz58pS8/87gPouhyjHyiQSsZ96th3nHq1sJPjGMNloyYoX3Kx3ykgYnJ1/N75BAcVq0iYBWFC2gnm06OiD7ME9ePMFc1dfFfl443/o=
  bucket: dictionary-artifacts
  local-dir: artifacts
  upload-dir: acctdictionary/$TRAVIS_BRANCH
  skip_cleanup: true
  on:
    repo: uc-cdis/ACCOuNT_dictionary
    all_branches: true
